// <auto-generated />
using System;
using ExampleTest2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExampleTest2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250610122549_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExampleTest2.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MapId");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Name = "Chinatown",
                            Type = "Large"
                        });
                });

            modelBuilder.Entity("ExampleTest2.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<decimal?>("BestRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            BestRating = 20.52m,
                            MapId = 1,
                            MatchDate = new DateTime(1950, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 20,
                            Team2Score = 10,
                            TournamentId = 1
                        });
                });

            modelBuilder.Entity("ExampleTest2.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BirthDate = new DateTime(1950, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Juziek",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            PlayerId = 2,
                            BirthDate = new DateTime(1950, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joanna",
                            LastName = "Bosna"
                        },
                        new
                        {
                            PlayerId = 3,
                            BirthDate = new DateTime(1950, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Krzysiek",
                            LastName = "Wiosna"
                        });
                });

            modelBuilder.Entity("ExampleTest2.Models.PlayerMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MVPs")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Player_Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            PlayerId = 1,
                            MVPs = 1,
                            Rating = 15.1m
                        });
                });

            modelBuilder.Entity("ExampleTest2.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournament");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            EndDate = new DateTime(1970, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "World Championship",
                            StartDate = new DateTime(1970, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ExampleTest2.Models.PlayerMatch", b =>
                {
                    b.HasOne("ExampleTest2.Models.Match", "match")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExampleTest2.Models.Player", "player")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("match");

                    b.Navigation("player");
                });

            modelBuilder.Entity("ExampleTest2.Models.Match", b =>
                {
                    b.Navigation("PlayerMatches");
                });

            modelBuilder.Entity("ExampleTest2.Models.Player", b =>
                {
                    b.Navigation("PlayerMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
